### ISSUE TITLE
LightGBM Shap values

### ISSUE THREAD

**Issue by philmassie** [Azure/mmlspark#1070]
Hello
Apologies if this is asked and answered elsewhere, I couldn't find it.
I'm struggling to understand how to use the getFeatureShaps() method of an MMLSpark LightGBM model. Specifically how to pass in the dense vectors of the background sample. I'm sure I'm being dumb, but I cant figure it out.

I wrongly assumed that I could pass a column of vectors, but that doesnt work. Is there an example somewhere please?

I'm loading "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3"

Thanks in advance
Actually, I'm not certain if this is even the correct place to ask questions - so apologies if it is not.

**Comment by philmassie** [comment]
Nm, I actually only just saw I am mixing up my versions.  was loading rc1 - Apologies

**Comment by imatiach-msft** [comment]
@philmassie LightGBM uses SHAP TreeExplainer, it uses the tree structure of the lightgbm model as the background data.  You don't need to pass any background/initialization examples like with the KernelExplainer.

**Comment by imatiach-msft** [comment]
see paper from Scott Lundberg on TreeExplainer:
https://www.nature.com/articles/s42256-019-0138-9.epdf?shared_access_token=RCYPTVkiECUmc0CccSMgXtRgN0jAjWel9jnR3ZoTv0O81kV8DqPb2VXSseRmof0Pl8YSOZy4FHz5vMc3xsxcX6uT10EzEoWo7B-nZQAHJJvBYhQJTT1LnJmpsa48nlgUWrMkThFrEIvZstjQ7Xdc5g%3D%3D

please see shap tree explainer examples:
https://github.com/slundberg/shap#treeexplainer

**Comment by imatiach-msft** [comment]
for lightgbm in mmlspark, you have two options:

1.) call getFeatureShaps on a vector directly
2.) when calling predict on model, set featuresShapCol="my output column":
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/params/LightGBMParams.scala#L246
then after calling transform on model one of the columns in output dataset will contain shap local importance values for every test dataset example

**Comment by philmassie** [comment]
Thanks so much @imatiach-msft for the fast response, and for the references. Oh and for the awesomeness of LightGBM in Spark!!!
Ok I see now where I was going wrong, I never saw that I should set it in the predict call! that's perfect! I was trying to send it a column of vectors lol.
Really very grateful for all the incredible work being done here, thanks again and apologies for missing that.

**Comment by philmassie** [comment]
For anyone else who's similarly lost like I was. You need to declare the featuresShapCol="my output column" in your model definition, eg.
```
lgb_shap = LightGBMClassifier(
    featuresCol = "your_features", labelCol="your_lbl", objective='binary', **featuresShapCol="shap_values"**)
```
then your subsequent transforms will include the tree explainer based Shap scores - which is so cool. 
Thanks for this again :)

**Comment by kishoresurana** [comment]
@philmassie, @imatiach-msft, thank you for sharing the snippet above to retrieve the shap_values (by calling .select("shap_values")). 

Can you please also provide code sample snippet that does this, to visualize the shap values - "_then your subsequent transforms will include the tree explainer based Shap scores - which is so cool._"?

I'm trying to visualize the shap values as shown below, but running into an error as shown below.
https://github.com/slundberg/shap

import shap
shap.plots.waterfall(shap_values)
_**Error:** : AttributeError: 'DataFrame' object has no attribute 'base_values'_

**Comment by imatiach-msft** [comment]
@kishoresurana I believe, based on that error, you will need to convert the spark dataframe to a numpy array.  Then, I believe you should be able to use the shap plots directly.

**Comment by philmassie** [comment]
@kishoresurana, I am sorry but I dont have a simple way to test this right now. As @imatiach-msft says though I think the datatype is wrong for plots etc.

The `select("shap_values")` bit returns a Spark DataFrame, but for plotting you need to collect the data back into your driver's Python context (as opposed to the Spark context/session). Something like this might get you closer (but watch out for scale):
```
import numpy as np
yourarray = np.array(od_lgb_shap.transform(test).select("shap_values").collect())
```

The plotting functions from the slunberg/shap library are all written around Numpy data structures I suspect, which are returned from the Python version of LightGBM, not the Spark version.

I hope that makes some sense and is helpful (and isn't wrong :))

**Comment by kishoresurana** [comment]
@philmassie , @imatiach-msft , thank you so much for trying to help. I honestly didn't expect that you folks would respond!

See code below (if you like to repro), which should be self-contained once you install the corresponding packages.
Basically, the shap plot is throwing an error expecting "base_values". Any idea how to get this working? @philmassie, could you share some code on how you use the shap_values? I struggle because trying to use LightGBM along with shap and other packages has a lot of gotchas.. :(


`
\# following this code: https://github.com/microsoft/SynapseML/blob/master/notebooks/features/lightgbm/LightGBM%20-%20Overview.ipynb

import shap
import numpy as np
from pyspark.ml.functions import vector_to_array
from pyspark.ml.feature import VectorAssembler
from mmlspark.lightgbm import LightGBMClassifier # unable to install synapse.ml in Azure synapse analytics environment

\# read data
df = spark.read.format("csv")\
  .option("header", True)\
  .option("inferSchema", True)\
  .load("wasbs://publicwasb@mmlspark.blob.core.windows.net/company_bankruptcy_prediction_data.csv")

\# split to train, test
df_train, df_test = df.randomSplit([0.85, 0.15], seed=1)

\# get names of feature cols
feature_cols = df.columns[1:]

\# what does this do?
featurizer = VectorAssembler(
    inputCols=feature_cols,
    outputCol='features'
)

\# transforms train data. but what does it exactly do?
train_data = featurizer.transform(df_train)['Bankrupt?', 'features']

\# transforms test data. but what does it exactly do?
test_data = featurizer.transform(df_test)['Bankrupt?', 'features']

\# initialize model
model_3 = LightGBMClassifier(objective="binary", featuresCol="features", labelCol="Bankrupt?", isUnbalance=True, featuresShapCol="shap_values")

\# fit model to train data
model_3 = model_3.fit(train_data)

\# transform on test_data to get shap_values. this is confusing since you use test to make a prediction. oh well, maybe getting shap_values instead of prediction?
shap_values_3 = model_3.transform(test_data).select("shap_values") #.show(truncate=False)

\# transform dataframe with pyspark VectorUDT to numpy array
shap_values_np_3 = np.array(shap_values_3.select(vector_to_array("shap_values").alias("shap_values")).collect())

\# lookks like an unnecessary axis got added? removing it
shap_values_np_3 = np.squeeze(shap_values_np_3, axis=1)


**\# visualize the first prediction's explanation
shap.plots.waterfall(shap_values_np_3)
\##### Fails with error - AttributeError: 'numpy.ndarray' object has no attribute 'base_values'
\##### How to get base_values object values? for shap!? Can someone help?**

`

**Comment by seakelle** [comment]
Also having some interesting issues with SHAP values calculated via SynapseML. It appears that there's an extra value added that does not correspond to any of the input features. Perhaps that's why the top features appear so different @kishoresurana? I'm including a snippet below which extends your example from above and compares the SynapseML SHAP values to SHAP values calculated by the native `shap` package.
```py
import shap
import numpy as np
from pyspark.ml.functions import vector_to_array
from pyspark.ml.feature import VectorAssembler
from mmlspark.lightgbm import LightGBMClassifier # unable to install synapse.ml in Azure synapse analytics environment
import lightgbm as lgb

# read data
df = spark.read.format("csv").option("header", True).option("inferSchema", True).load("wasbs://publicwasb@mmlspark.blob.core.windows.net/company_bankruptcy_prediction_data.csv")

# split to train, test
df_train, df_test = df.randomSplit([0.85, 0.15], seed=1)

# get names of feature cols
feature_cols = df.columns[1:]

# what does this do?
featurizer = VectorAssembler(
inputCols=feature_cols,
outputCol='features'
)

# transforms train data. but what does it exactly do?
train_data = featurizer.transform(df_train)['Bankrupt?', 'features']

# transforms test data. but what does it exactly do?
test_data = featurizer.transform(df_test)['Bankrupt?', 'features']

# initialize model
model_3 = LightGBMClassifier(objective="binary", featuresCol="features", labelCol="Bankrupt?", isUnbalance=True, featuresShapCol="shap_values")

# fit model to train data
model_3 = model_3.fit(train_data)

###############################
# mmlspark shap values
###############################

# get predictions
predictions = model_3.transform(test_data)

# transform on test_data to get shap_values
shap_values_3 = predictions.select("shap_values")

# transform dataframe with pyspark VectorUDT to numpy array
shap_values_np_3 = np.array(shap_values_3.select(vector_to_array("shap_values").alias("shap_values")).collect())

# lookks like an unnecessary axis got added? removing it
mmlspark_shap_values = np.squeeze(shap_values_np_3, axis=1)

# display summary plot
shap.summary_plot(mmlspark_shap_values, max_display=500, feature_names=feature_cols)
# -> File "/home/trusted-service-user/cluster-env/env/lib/python3.8/site-packages/shap/plots/_beeswarm.py", line 880, in <listcomp>
# ->     pl.yticks(range(len(feature_order)), [feature_names[i] for i in feature_order], fontsize=13)
# -> IndexError: list index out of range

###############################
# shap library shap values
###############################

# get lgbm booster
booster_model_str = model_3.getLightGBMBooster().modelStr().get()
booster = lgb.Booster(model_str=booster_model_str)
booster.params['objective'] = 'binary'

# convert spark df to pandas
df_test_X = df_test.select(*feature_cols).toPandas()

# calculate shap values
native_shap_values = shap.TreeExplainer(booster).shap_values(df_test_X)

# display summary plot
shap.summary_plot(shap_values_np_3, max_display=500, feature_names=feature_cols)
# -> succeeds

###############################
# debugging
###############################

# features (95 values)
print(len(feature_cols))
# -> 95
print(len(train_data.select('features').collect()[0][0]))
# -> 95

# mmlspark shap (96 values)
print(len(predictions.select('shap_values').collect()[0][0]))
# -> 96
print(shap_values_np_3.shape)
# -> (1034, 1, 96)
print(mmlspark_shap_values.shape)
# -> (1034, 96)

# native shap (95 values)
print(np.array(native_shap_values).shape)
# -> (2, 1034, 95)

# mmlspark shap values equivalent to native shap values after remove extra column
print((native_shap_values[1] == mmlspark_shap_values))
# -> elementwise comparison failed; this will raise an error in the future.
print((native_shap_values[1] == mmlspark_shap_values[:, :-1]).all())
# -> True

# extra shap value with only unique value from mmlspark
print(np.unique(mmlspark_shap_values[:, -1]))
# -> [1.16682832]
```

This singular unique value is clearly noticeable in the top row of the [feature importance summary plot](https://imgur.com/a/rS3Z08N) you posted above as well. I don't think there's a bug in how you convert the SynapseML SHAP values to numpy because if we remove the extra value, the arrays are identical.

**Comment by imatiach-msft** [comment]
@seakelle the extra value is the expected value, or what the model predicted on the background dataset - you can think of it as what the model predicted if all features were "off" in the sense that they would be replaced with the background distribution (ie the average of the training dataset or the population).

**Comment by seakelle** [comment]
Understood. Thanks for the quick response! Would it be possible to make this clearer in the documentation? Especially since the `VectorAssembler` is needed to aggregate the features into one column and thus the feature names become slightly obfuscated, it easy to mistake that the extra value is associated with one of the input features.
