### ISSUE TITLE
New release and Spark 3

### ISSUE THREAD

**Issue by awichera** [Azure/mmlspark#1114]
**Is your feature request related to a problem? Please describe.**
Spark 2 will be soon discontinued in Databricks and other platforms. Spark 3 is more than year old at this point

**Describe the solution you'd like**
New official release of MMLSpark, that would support low latency serving of Spark 3 MLlib models with Spark Serving

**Additional context**

Latest release proper seems to be v0.18.1 from Aug 20, 2019. There are serveral relases marked as rc after that. Latest from Oct 2, 2020.
Even though repository seems to be actively maintained.

It would be great to know, what are the plans with MMLSpark in near future. If the repository will be actively maintained and if there will be regular releases.

----------

This library seems great but abscence of Spark 3 stops us from using it on all our projets. 

Keep up the good work though.

----------
By the way I am kind of suprised, that there is not a plenty of questions about Spark 3 support and release frequency. Maybe I am just missing something?

**Comment by chengyin38** [comment]
Would also love an update on Spark 3 support timeline.

**Comment by mhamilton723** [comment]
Spark 3 already supported though we haven't cut the release due to largely bureaucratic reasons ;). The official cut will be coming in the next month or so.

The latest master coordinates are:

MMLSpark Build and Release Information
Maven Coordinates
com.microsoft.ml.spark:mmlspark:1.0.0-rc3-148-87ec5f74-SNAPSHOT

Maven Resolver
https://mmlspark.azureedge.net/maven

Documentation Pages:
Scala Documentation: https://mmlspark.blob.core.windows.net/docs/1.0.0-rc3-148-87ec5f74-SNAPSHOT/scala/index.html
Python Documentation : https://mmlspark.blob.core.windows.net/docs/1.0.0-rc3-148-87ec5f74-SNAPSHOT/pyspark/index.html

**Comment by leedabee** [comment]
@mhamilton723 checking in on the status here. Any updates with Spark 3 release?

**Comment by limbXo** [comment]
> Spark 3.1.2 is supported on master though we haven't cut the release due to largely bureaucratic reasons ;). The official cut will be coming in the next month or so.
> 
> The latest master coordinates are:
> 
> MMLSpark Build and Release Information Maven Coordinates com.microsoft.ml.spark:mmlspark:1.0.0-rc3-148-87ec5f74-SNAPSHOT
> 
> Maven Resolver https://mmlspark.azureedge.net/maven
> 
> Documentation Pages: Scala Documentation: https://mmlspark.blob.core.windows.net/docs/1.0.0-rc3-148-87ec5f74-SNAPSHOT/scala/index.html Python Documentation : https://mmlspark.blob.core.windows.net/docs/1.0.0-rc3-148-87ec5f74-SNAPSHOT/pyspark/index.html

Looks like this coordinate is outdated. What is the newest coordinate and can I find them myself?
