### ISSUE TITLE
I want to know how to get a DNN model using mmlspark

### ISSUE THREAD

**Issue by alg-jmx** [Azure/mmlspark#155]
I has seen many examples with loading DNN model,But I want to know how to get a DNN model using mmlspark?

**Comment by mhamilton723** [comment]
Hey, I'm not quite sure what you mean by "get a DNN model", we curate a collection of pre-trained models you can download, use, and inspect in the `ModelDownloader` class. You can also train your own CNTK model or grab a model from that repo and bring it into the spark ecosystem.

**Comment by alg-jmx** [comment]
I just want to know how to get my own training CNTK model. Is there any demos?

**Comment by mhamilton723** [comment]
https://github.com/Microsoft/CNTK/blob/v2.2/Examples/Image/Classification/MLP/Python/SimpleMNIST.py

here is an example of training a model in CNTK. Once this model is trained you can save it to HDFS or a local file, then point the MMLSpark CNTKModel to it so that it can load it and execute it in parallel for deployment. Hope this helps!

**Comment by imatiach-msft** [comment]
you can also train with an attached GPU VM to spark with CNTKLearner, see here:
https://github.com/Azure/mmlspark/blob/gpu/docs/azure-setup.md
you will need to setup the GPU branch though, which we will be releasing to master soon.

**Comment by imatiach-msft** [comment]
you can see the example here:
https://github.com/Azure/mmlspark/blob/gpu/notebooks/gpu/401%20-%20CNTK%20train%20on%20HDFS.ipynb
We will also soon be adding a parquet reader to CNTK with a new example
