### ISSUE TITLE
LightGBMBooster's mergeModel function works?

### ISSUE THREAD

**Issue by ywskycn** [Azure/mmlspark#315]
I was playing around the mergeModels function. The following function looks like not change the first booster, as it always creates a new LightGBMBooster using the old "model" value. Do I miss anything there?
```
  def mergeModels(newModel: LightGBMBooster): LightGBMBooster = {
    // Merges models to first handle
    if (model != null) {
      LightGBMUtils.validate(
        lightgbmlib.LGBM_BoosterMerge(getModel(), newModel.getModel()),
        "Booster merge")
    }
    new LightGBMBooster(model)
  }
```

**Comment by imatiach-msft** [comment]
@ywskycn yes, I think we discussed over email already, but we aren't merging models (they should be the same after doing distributed training supposedly).
This function isn't actually used, it was merging models previously but since the code changed at some point in history the logic doesn't make sense anymore, I think we should remove the function altogether.
Thanks for catching this!

**Comment by ywskycn** [comment]
Thanks for the explanation, @imatiach-msft . Created https://github.com/Azure/mmlspark/pull/316 for removing this function.
