### ISSUE TITLE
getting error in LightGBMClassifier on databricks with pyspark

### ISSUE THREAD

**Issue by robertobigdata** [Azure/mmlspark#328]
Hello, I've installed mmlspark using Maven Coordinates. I'm using a cluster with spark 2.1.
But I'm not able of making LightGBMClassifier to work.

My code is this, but always getting the same error, So I have to start from the beginning.

![mmlspark_error](https://user-images.githubusercontent.com/32799774/41812440-11f5222a-7723-11e8-9e68-b3b58f460d78.png)

And if I execute only LightGBMClassifier fit part, I get this one:
'The spark driver has stopped unexpectedly and is restarting. Your notebook will be automatically reattached.'

I would appreciate if someone could help me.

Thank you.

**Comment by imatiach-msft** [comment]
@robertobigdata hi, sorry for the trouble, there have been several fixes to lightgbm - does using the following build fix your issue (you will need to specify the repository as our maven build repo):
--packages com.microsoft.ml.spark:mmlspark_2.11:0.12.dev21+4.g90b0ddc
--repositories https://mmlspark.azureedge.net/maven
Otherwise, if you are still having issues, if you could send us a public dataset and some example code we could debug the issue (note: there is currently a known issue with quantile regression that I am investigating, but it looks like it shouldn't be related to your example)

**Comment by mhamilton723** [comment]
@robertobigdata, Thanks for raising this, if the 0.13 update does not fix this issue please feel free to re-open this issue.
