### ISSUE TITLE
Datasets for running LightGBM tests

### ISSUE THREAD

**Issue by superbobry** [Azure/mmlspark#383]
I apologise in advance if this is documented somewhere, but I did my best to look it up and did not find anything relevant.

In order to run LightGBM tests, one has to define the `$DATASETS_HOME` environment variable which 
 I think, should point to a directory with binary/multiclass/regression training data for various well-known datasets. I assume that the developers working on mmlspark have all of this set up, but it is not clear how to go about bootstraping the testing environment from scratch. 

Could you kindly point me to an existing repo/script doing this? If such script does not exist, do you think it might be a good idea to write one or ship the data directly as test resources?

**Comment by imatiach-msft** [comment]
Hi @superbobry, you can run the ./runme script which will define the $DATASETS_HOME variable and download the dataset, you can find the instructions here: https://github.com/Azure/mmlspark/blob/master/docs/developer-readme.md
Note the dev setup only works in Linux currently because it depends on bash.  I think there was some discussion about how that could improved to support other envs in the future that @mhamilton723 and @elibarzilay (who is working on a different team now) might have more context on.  Note you will need to run ./runme twice and the second time you will need to relogin to the shell since new environment variables will be defined in the bashrc file.

**Comment by superbobry** [comment]
Hi @imatiach-msft, thank you very much for the reply. 

I am running macOS, and it seems the main blocker for porting `./runme` is cntk which is only available/prebuilt for Windows and Linux.

For the record, the dataset archive `./runme` fetches is available here: https://mmlspark.azureedge.net/installers/datasets-2017-05-25.tgz
