### ISSUE TITLE
Single Column Bug

### ISSUE THREAD

**Issue by ishengyang** [Azure/mmlspark#423]
Sometimes, when I have only 1 feature, the .fit() process fails with a bug.
However, if I combine 2 or more such bugged features, the .fit() process won't fail. 

Here is the beginning of the error message when it fails.

Py4JJavaError: An error occurred while calling o1063.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 154.0 failed 4 times, most recent failure: Lost task 2.3 in stage 154.0 (TID 791, 10.231.246.65, executor 3): java.util.NoSuchElementException: key not found: 3

**Comment by imatiach-msft** [comment]
@ishengyang Sorry about the issues you are having.  I think this is a different issue which has been fixed:
https://github.com/Azure/mmlspark/pull/399
Please also see:
https://github.com/Azure/mmlspark/issues/406
and related issue:
#397
However, the fix was after the 0.14 release, it should be in 0.15.  You can use the latest build from master instead, eg:

--packages
 com.microsoft.ml.spark:mmlspark_2.11:0.14.dev13+1.g58a2027c
 and --repositories
https://mmlspark.azureedge.net/maven

**Comment by imatiach-msft** [comment]
@ishengyang closing this issue, please let us know if you are still seeing it in v0.16
