### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not load the native libraries because we encountered the following problems: no _lightgbm in java.library.path and Could not find resource /com/microsoft/ml/lightgbm/osx/x86_64/lib_lightgbm.dylib in jar.

### ISSUE THREAD

**Issue by RayTsui** [Azure/mmlspark#452]
Whether or not there is solution for running lightgbm on spark(scala) on mac. After I call LightGBMRegressor on scala spark context on mac, it shows the following issue:

java.lang.UnsatisfiedLinkError: Could not load the native libraries because we encountered the following problems: no _lightgbm in java.library.path and Could not find resource /com/microsoft/ml/lightgbm/osx/x86_64/lib_lightgbm.dylib in jar.

Thanks for figuring out.

**Comment by imatiach-msft** [comment]
@RayTsui sorry, this is a known issue:
https://github.com/Azure/mmlspark/issues/290
we don't yet support MacOS, but it's something that we would like to add.  First, we need to add SWIG support for MacOS in LightGBM repo.

**Comment by RayTsui** [comment]
Hi @imatiach-msft , thank you for your follow-up. Once lightGBM is available on mac in the future. Please make it known in community.

**Comment by shuDaoNan9** [comment]
By the way, I got this exception on linux too, because I forgot to add 'lightgbmlib-3.3.510.jar'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the native libraries because we encountered the following problems: no _lightgbm in java.library.path and Could not find resource /com/microsoft/ml/lightgbm/linux/x86_64/lib_lightgbm.so in jar.

**Comment by shuDaoNan9** [comment]
sorry, how to close this issue
