### ISSUE TITLE
This lib can not support categorical feature?

### ISSUE THREAD

**Issue by charmby** [Azure/mmlspark#519]
I didn't find any interface  to support this functions. i can find in sklearn

**Comment by imatiach-msft** [comment]
hi @charmby , actually we do support categorical slot names or indexes, please see the documentation here:

http://mmlspark.azureedge.net/docs/scala/index.html#com.microsoft.ml.spark.LightGBMClassifier@setCategoricalSlotIndexes(value:Array[Int]):LightGBMParams.this.type

**Comment by imatiach-msft** [comment]
You can pass an array of indexes or slot names for the features vector column that lightgbm takes in and they will be natively treated as categorical:

def setCategoricalSlotIndexes(value: Array[Int]): LightGBMClassifier.this.type
def setCategoricalSlotNames(value: Array[String]): LightGBMClassifier.this.type

Alternatively, if you use string indexer or our value indexer, categorical metadata will be automatically added to the dataframe and lightgbm will actually be able to interpret it and treat those columns as categoricals by splitting on the feature values directly (so you won't need to one-hot-encode them)

**Comment by imatiach-msft** [comment]
sorry, did you mean lightgbm specifically or the library in general?  Spark ML supports categoricals with StringIndexer and we have our own ValueIndexer implementation.

**Comment by imatiach-msft** [comment]
@charmby closing this issue as we do support categoricals, both in mmlspark (and many of the algorithms such as lightgbm) and in Spark ML, please feel free to reopen if you are still having this issue.

**Comment by jwgwalton** [comment]
@imatiach-msft 

Hi, i'm trying to use the native categorical variable support rather than one hot encoding them. I've tried using both  the normal spark StringIndexer and VectorAssembler  and the mmlspark ValueIndexer and FastVectorAssembler but keep getting the following stack trace (this is in python btw)

Py4JJavaError: An error occurred while calling o179.fit.
: java.lang.UnsupportedOperationException: Unsupported Categorical type FloatType
	at com.microsoft.ml.spark.ValueIndexer.fit(ValueIndexer.scala:75)
	at com.microsoft.ml.spark.TrainClassifier.convertLabel(TrainClassifier.scala:224)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:99)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Both the normal spark and mmlspark vector assemblers require numerically encoded categorical variables, however both of the indexers convert to floats. What am i missing here?

**Comment by imatiach-msft** [comment]
@jwgwalton 
For that specific error in ValueIndexer, the error is coming from here:
https://github.com/Azure/mmlspark/blob/7eed833156f507357c8b43aefcf77ddfab0f2be9/src/value-indexer/src/main/scala/ValueIndexer.scala#L75

it looks like you have floating point values instead of ints/strings that you are trying to convert to categoricals.  If the dataset is not confidential, would you be able to share the values that are in that column or some similar open dataset that has the same issue?
I think it would be easy to add floating point type support for indexing categoricals but it just seems a bit weird to have floats like 1.2, 2.5, etc treated as categoricals which have no concept of ordering.  What is the use-case here specifically?

**Comment by imatiach-msft** [comment]
If you have floats like 1,2,3 etc. in that column (one of the ℕ natural numbers) then you could just convert the column to int in spark
