### ISSUE TITLE
java.lang.Exception: Please score the model prior to evaluating

### ISSUE THREAD

**Issue by konabuta** [Azure/mmlspark#522]
Try to use ComputeModelStatistics to LightGBMClassifier model and failing with error java.lang.Exception. Any Comments would be appreciated.

To reproduce this error
1. Unzip attached file
2. load Factory.csv to Spark Dataframe
3. Run program in html
[issue.zip](https://github.com/Azure/mmlspark/files/3012362/issue.zip)

**Comment by imatiach-msft** [comment]
@konabuta this is by design, you did not provide the scored labels column to ComputeModelStatistics or set it on the dataframe metadata, there are several solutions here:
1.) You can provide the scored labels column to ComputeModelStatistics (scoredLabelsCol="my_favorite_column"), and if you want to compute AUC as well you will need to provide the scores column (scoresCol="my_favorite_scores_col")
2.) You can use TrainClassifier or TrainRegressor with LightGBMClassifier or LightGBMRegressor and that will automatically add the metadata for you
3.)  You can use the Spark ML evaluators instead (but you will also need to provide the scored labels column to them)

**Comment by konabuta** [comment]
Thank you for your help ! It works.
