### ISSUE TITLE
AML Compute job failing

### ISSUE THREAD

**Issue by snelso1** [Azure/mmlspark#655]
FYI.. one of my AML Compute jobs just started failing with the below error message.  I tried reverting back to 0.17 but that version appears untagged so I went back to 0.16 and that appears to be working.

For reference this is how our Estimator script was defined that was failing:
roll_estimator = Estimator(
    source_directory="./compute",
    entry_script="roll.py",
    script_params={},
    compute_target=compute_target_spark,
    conda_packages=['pyspark', 'pandas', 'numpy'],
    pip_packages=['pip', 'findspark'],
    custom_docker_image='microsoft/mmlspark:latest'
)

![spark_home_error](https://user-images.githubusercontent.com/1169037/63375100-f9094100-c33f-11e9-9555-f9f9c1603dba.png)

**Comment by imatiach-msft** [comment]
@snelso1  sorry about the trouble you are having.  This looks like it's related to azure machine learning service and not mmlspark (the custom docker image has the same name but it's just AML services reusing the lightweight docker that was formerly built by mmlspark devs and not related to this open source project).  Feel free to open the bug here:
https://github.com/Azure/MachineLearningNotebooks
