### ISSUE TITLE
How to set features' name in a LightGBM model

### ISSUE THREAD

**Issue by ocworld** [Azure/mmlspark#740]
How to set feature's column name in a LightGBM model?

My dataset already have 'features' sparse vector column to train a model.

I wanna set features' name in model string like python train API's parameter named as feature_name.

**Comment by imatiach-msft** [comment]
hi @ocworld, sorry about the trouble you are having. In the pyspark API for a trained model currently there is an issue here:
https://github.com/Azure/mmlspark/issues/721
the workaround is to use:

model._java_obj.setPredictionCol('alternate_prediction')
model._java_obj.setFeaturesCol('alternate_features')
model._java_obj.setLabelCol('alternate_label')

**Comment by ocworld** [comment]
Thank you for your response.

To understand my problem, I write additional comment.

In model string, feature names is written like that,
```
feature_names=Column_0 Column_1 Column_2 Column_3 Column_4 Column_5 Column_6 Column_7 Column_8 Column_9 Column_10 Column_11 Column_12 Column_13 Column_14 Column_15 Column_16
```

I hope to their feature_names like real column name I given.

My input dataset has only columns that are 'key', 'label', 'features (sparse vector)'.

How to set their names?

**Comment by imatiach-msft** [comment]
@ocworld you should be able to set the slot names on the vector column metadata (I believe the spark term is metadata attributes but I use slots as the term based on my previous experience with another ML library).  I believe VectorAssembler does this, but our implementation of FastVectorAssembler in mmlspark removes them due to performance issues.  How are you creating the features (sparse vector) column?
The code here might help to understand how the slot names are passed from the metadata to lightgbm:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L48
If it's not working there might be a bug here.

**Comment by ocworld** [comment]
It is resolved
