### ISSUE TITLE
Mini-batch inference can improve speed of the inference stage

### ISSUE THREAD

**Issue by aleph-null84** [Azure/mmlspark#814]
Hello!

Recently, I have tried the LightGBMClassifier model in our ML tasks. It have shown excellent predictive performance. But I have noticed quite slow inference stage of the model. I think, that You can significantly improve the speed of the inference stage by using mini-batch inference instead of row-wise. Namely, You can select a mini-batch of input records from the Spark dataset, and then apply the native LGBM_BoosterPredictForMat method to whole mini-batch. Similar functionality is implemented in the XGBoost4J and DL4J.

BR

**Comment by imatiach-msft** [comment]
@aleph-null84 there was a regression which caused some 3-4x performance improvements during inference to be reverted by accident when they introduced a bug, it has been fixed in latest lightgbm here:
https://github.com/microsoft/LightGBM/pull/2799
but I need to update mmlspark to latest lightgbm which I am currently working on

**Comment by imatiach-msft** [comment]
Closing as lightgbm has been updated on master with the fix for the scoring execution time regression.
Also, there are more optimizations being added here for prediction, which will be available in the future:
https://github.com/microsoft/LightGBM/pull/2992
