### ISSUE TITLE
how to get lightgbm 2.2.350 source code

### ISSUE THREAD

**Issue by canli12138** [Azure/mmlspark#825]
i want to use mmlspark on ARM platform, so i need to compile lightgbmlib-2.2.350.jar on the ARM,but i don't know how to get the source code of 2.2.350 version

**Comment by imatiach-msft** [comment]
@canli12138 , sorry, will try to keep better track of the change sets.  In the PR merged today I mentioned the change set used:
https://github.com/Azure/mmlspark/pull/850
will do this moving forward.
I think this issue was already answered here:
https://github.com/microsoft/LightGBM/issues/2900
There was also a discussion here:
https://github.com/microsoft/LightGBM/issues/3041

Copying a previous post in case it helps:

it looks like I created 2.3.150 on Dec 9. Note that while I don't keep track of the exact commit I do copy all of the source over to the jar when I release it, although it's only limited to the *.java files which may not be as useful:

drwxrwxr-x 2 ilya ilya 4.0K Aug 22 2018 DeployLightGBM-2.1.200
drwxrwxr-x 2 ilya ilya 4.0K Aug 26 2018 DeployLightGBM-2.1.250
drwxrwxr-x 2 ilya ilya 4.0K Dec 13 2018 DeployLightGBM-2.2.200
drwxrwxr-x 2 ilya ilya 4.0K Mar 20 2019 DeployLightGBM-2.2.300
drwxrwxr-x 2 ilya ilya 4.0K Apr 30 2019 DeployLightGBM-2.2.350
drwxrwxr-x 2 ilya ilya 4.0K Aug 29 2019 DeployLightGBM-2.2.400
drwxrwxr-x 2 ilya ilya 4.0K Oct 8 2019 DeployLightGBM-2.3.100
drwxrwxr-x 2 ilya ilya 4.0K Dec 9 01:05 DeployLightGBM-2.3.150
drwxrwxr-x 2 ilya ilya 4.0K Mar 29 15:16 DeployLightGBM-2.3.160
drwxrwxr-x 2 ilya ilya 4.0K Apr 3 00:59 DeployLightGBM-2.3.170

I think changeset b6aa5ee might have been it, but I'm not 100% sure.

As long as you have this fix you should be fine:

image

**Comment by imatiach-msft** [comment]
closing issue, please reopen if you have any other questions
