### ISSUE TITLE
Unable to import LightGBMRegressor

### ISSUE THREAD

**Issue by nataliabernardo** [Azure/mmlspark#910]
I installed the library with "pip install mmlspark" with no issues, however when I try importing 'LightGBMRegressor' (from mmlspark import LightGBMRegressor), I get the messag bellow

ImportError: cannot import name 'ValidatorParams' from 'pyspark.ml.tuning' (/databricks/spark/python/pyspark/ml/tuning.py)

**Comment by imatiach-msft** [comment]
@nataliabernardo it seems this class was made private recently in spark:
https://github.com/apache/spark/commit/67e1360bade9ef7691746f63ca99411cfe9d249b#diff-cbc8c36bfdd245e4e4d5bd27f9b95359R125
are you using spark 3.0?  Can you try 2.X version of spark?  Otherwise there was just an underscore added to the class, so maybe importing with underscore might be a workaround for now.  What is the stack trace for the error?

I only see this used in two files not related to LightGBMRegressor in mmlspark:
https://github.com/Azure/mmlspark/search?q=ValidatorParams&unscoped_q=ValidatorParams
I don't understand how it's getting imported, so if you see a stack trace that might help diagnose the issue.

**Comment by nataliabernardo** [comment]
@imatiach-msft thank you for the recommendation. I changed the version of spark from 3.0 to 2.x and it worked :) Thanks a lot!

**Comment by cosmincatalin** [comment]
Hi, downgrading to 2.x will of course work, but how can we make this work on 3.x?

I'm not sure I understand your suggestion with "importing with underscore might be a workaround". Can you elaborate?
